server:
  port: 8093

# Configuration for MySQL Database
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/proddb
    username: root
    password: Priya@1998
    driver-class-name: com.mysql.cj.jdbc.Driver

my:
  greeting: Hello World from cloud-prod